# Generated by Django 4.2.23 on 2025-09-30 18:30

from django.conf import settings
from django.db import migrations, models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


def forwards_func(apps, schema_editor):
    # This function is now empty as the data migration is no longer needed on a clean database.
    pass

def backwards_func(apps, schema_editor):
    # This function is now empty as the data migration is no longer needed on a clean database.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]