# Generated by Django 4.2.23 on 2025-10-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_organization_owner_alter_membership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='bic',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AddField(
            model_name='organization',
            name='iban',
            field=models.CharField(blank=True, default='', max_length=34),
        ),
    ]
