# Generated by Django 4.2.23 on 2025-10-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_plan_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
