# Generated by Django 4.2.23 on 2025-08-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='timeentry',
            options={'ordering': ['-start_time']},
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', 'name'], name='tracker_pro_user_id_ada997_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['user', 'start_time'], name='tracker_tim_user_id_0eb9c0_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['user', 'category'], name='tracker_tim_user_id_e471c9_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['is_archived', 'is_hidden'], name='tracker_tim_is_arch_92332b_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentryimage',
            index=models.Index(fields=['time_entry'], name='tracker_tim_time_en_5dbd1e_idx'),
        ),
    ]
