# Generated by Django 4.2.23 on 2025-08-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_project_options_alter_timeentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('work', 'Work'), ('personal', 'Personal')], default='work', max_length=10),
        ),
    ]
