# Generated by Django 4.2.23 on 2025-08-22 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='accumulated_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
    ]
