# Generated by Django 4.2.23 on 2025-08-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_timeentry_accumulated_duration_timeentry_is_paused'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeentry',
            old_name='accumulated_duration',
            new_name='paused_duration',
        ),
        migrations.AddField(
            model_name='timeentry',
            name='last_pause_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
