# Generated by Django 4.2.23 on 2025-08-22 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_remove_timeentry_last_pause_time_pauselog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PauseLog',
            new_name='PauseResumeLog',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='is_paused',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='paused_duration',
        ),
    ]
