# Generated by Django 4.2.23 on 2025-08-22 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_rename_pauselog_pauseresumelog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='last_pause_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='paused_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.DeleteModel(
            name='PauseResumeLog',
        ),
    ]
