# Generated by Django 4.2.23 on 2025-08-22 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_timeentry_is_paused_timeentry_last_pause_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeentry',
            name='last_pause_time',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='paused_duration',
        ),
        migrations.CreateModel(
            name='PauseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pause_time', models.DateTimeField()),
                ('resume_time', models.DateTimeField(blank=True, null=True)),
                ('time_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pause_logs', to='tracker.timeentry')),
            ],
            options={
                'ordering': ['pause_time'],
            },
        ),
    ]
