# Generated by Django 4.2.23 on 2025-08-22 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_remove_timeentry_last_pause_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='last_pause_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='paused_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.DeleteModel(
            name='PauseLog',
        ),
    ]
