# Generated by Django 4.2.23 on 2025-08-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_timeentry_last_pause_time_timeentry_paused_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentryimage',
            name='image',
            field=models.ImageField(upload_to='time_entry_images/%Y/%m/%d/'),
        ),
    ]
