# Generated by Django 4.2.23 on 2025-08-22 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0012_alter_timeentryimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='tracker_pro_user_id_ada997_idx',
        ),
        migrations.RemoveIndex(
            model_name='timeentry',
            name='tracker_tim_user_id_0eb9c0_idx',
        ),
        migrations.RemoveIndex(
            model_name='timeentry',
            name='tracker_tim_user_id_e471c9_idx',
        ),
        migrations.RemoveIndex(
            model_name='timeentry',
            name='tracker_tim_is_arch_92332b_idx',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='is_hidden',
        ),
        migrations.AddField(
            model_name='project',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='tracker.project'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timeentryimage',
            name='image',
            field=models.ImageField(upload_to='time_entry_images/'),
        ),
    ]
