# Generated by Django 4.2.23 on 2025-08-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_alter_project_name_alter_project_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
    ]
