# Generated by Django 4.2.23 on 2025-08-28 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0016_timeentry_is_manual'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='timeentryimage',
            name='tracker_tim_time_en_5dbd1e_idx',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='is_manual',
        ),
        migrations.AddField(
            model_name='timeentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='time_entry_images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='tracker.project'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
