# Generated by Django 4.2.23 on 2025-08-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_remove_timeentry_image_project_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='was_edited',
            field=models.BooleanField(default=False),
        ),
    ]
