# Generated by Django 4.2.23 on 2025-10-07 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_alter_profile_address_alter_profile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='project',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='timeentryimage',
            name='time_entry',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='TimeEntry',
        ),
        migrations.DeleteModel(
            name='TimeEntryImage',
        ),
    ]
